import {CantileverParams} from "../../types/cantilever";

export const CantileversData: CantileverParams[] = [
  {
    id:1,
    external_id:"#01A-001",
    pole:"23A",
    pole_id:12,
    via:"#01A",
    via_id:1,
    location_id:24,
    location_name:"Patio Taller",
    user_id:12,
    created_by:"Dalton Chiarelli",
    created_at: new Date(),
    updated_at: new Date(),
    params: {
      type: "TDP<2.2",
      contact_wire_height: 4500,
      system_height: 1600,
      zig_zag: -150,
      upper_isolator_length: 262,
      bottom_isolator_length: 262,
      alpha_superior_tube: 4,
      alpha_registration_arm: 0,
      alpha_steady_arm: 0,
      bitola: 400,
      esc: 0,
      pv: 2150,
      wire_support_wire_to_tube_length: 123,
      wire_support_end_distance: 200,
      wire_support_to_eye_clamp_distance: 250,
      eye_clamp_eye_to_tube_length: 81,
      swivel_with_clevis_pole_to_pin_distance: 42,
      swivel_with_clevis_pin_to_fix_connection_length: 42,
      clevis_end_fitting_pin_to_tube_length: 54,
      cw_swivel_clip_holder: {
        eye_to_cw_x: 15.99,
        eye_to_cw_y: 100,
        angle_to_cw: 94,
      },
      steady_arm_end_point_distance: 40
    },
  },
  {
    id:2,
    external_id:"#01A-002",
    pole:"23A",
    pole_id:11,
    via:"#01A",
    via_id:1,
    location_id:24,
    location_name:"Patio Taller",
    user_id:13,
    created_by:"Dalton Chiarelli",
    created_at: new Date(),
    updated_at: new Date(),
    params: {
      type: "TDP<2.2",
      contact_wire_height: 4500,
      system_height: 1600,
      zig_zag: -150,
      upper_isolator_length: 262,
      bottom_isolator_length: 262,
      alpha_superior_tube: 4,
      alpha_registration_arm: 0,
      alpha_steady_arm: 0,
      bitola: 400,
      esc: 0,
      pv: 2150,
      wire_support_wire_to_tube_length: 123,
      wire_support_end_distance: 200,
      wire_support_to_eye_clamp_distance: 250,
      eye_clamp_eye_to_tube_length: 81,
      swivel_with_clevis_pole_to_pin_distance: 42,
      swivel_with_clevis_pin_to_fix_connection_length: 42,
      clevis_end_fitting_pin_to_tube_length: 54,
      cw_swivel_clip_holder: {
        eye_to_cw_x: 15.99,
        eye_to_cw_y: 100,
        angle_to_cw: 94,
      },
      steady_arm_end_point_distance: 40
    },
  }
];
